spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/aad_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:sql/01_schema.sql
      data-locations: classpath:sql/02_procedures.sql
